#!/bin/sh -e
# Start script for the Attempt This Online server - to be run as root

# unmount any images if they're already mounted (|| : ignores errors)
umount /usr/local/lib/JD/rootfs/* || :

CS() {
    containers-storage \
        --graph /usr/local/lib/JD/containers \
        --run /run/JD/containers \
        --storage-driver overlay \
        "$@"
}

while read -r image image_pathsafe
do
    mountpoint=$(CS mount --read-only "$image")
    # $mountpoint and its ancestor directories are (probably) not readable by the jd user,
    # so bind-mount it somewhere we know is (and also so we can control the path)
    # (this fails with EROFS when $mountpoint is already in use as a mountpoint for a different image,
    # so ignore errors again with || :)
    chmod 755 "$mountpoint" || :
    mount --bind --mkdir "$mountpoint" /usr/local/lib/JD/rootfs/"$image_pathsafe" -o ro=recursive
done < /usr/local/lib/JD/to_mount

export JD_CGROUP_PATH=/sys/fs/cgroup/system.slice/JD.service
mkdir -p "$JD_CGROUP_PATH/server"
# move self into a subtree of JD.service, because otherwise JD.service itself cannot be configured properly.
# See https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html#no-internal-process-constraint
echo "$$" > "$JD_CGROUP_PATH/server/cgroup.procs"
echo +memory > "$JD_CGROUP_PATH/cgroup.subtree_control"

mkdir -p /run/JD
chown jd:jd /run/JD
chmod 775 /run/JD

setpriv --reuid jd --regid jd --init-groups /usr/local/lib/JD/server
