#!/bin/sh

systemctl disable --now JD.service nginx.service
sed -i '/systemctl stop nginx && certbot renew && systemctl start nginx/d' /var/spool/cron/root
umount /usr/local/lib/JD/rootfs/*
containers-storage wipe --graph /usr/local/lib/JD/containers --run /run/JD/containers
userdel jd
umount /usr/local/lib/JD/containers/overlay
rm -rf \
    /run/JD \
    /var/cache/JD \
    /var/lib/JD_home \
    /usr/local/bin/JD \
    /usr/local/lib/JD \
    /usr/local/share/JD \
    /usr/local/lib/systemd/system/JD.service \
    /usr/local/lib/systemd/system/JD.socket
