#!/bin/sh

cd /ATO/context
if [ -f /opt/go.mod ]; then
    cp /opt/go.mod /opt/go.sum /ATO/
else
    echo "module ato" > /ATO/go.mod
    echo "go 1.22" >> /ATO/go.mod
    touch /ATO/go.sum
fi
ln -s /ATO/code /ATO/code.go
mkdir /ATO/tmp
export TMPDIR=/ATO/tmp GOCACHE=/ATO/tmp
export CGO_ENABLED=0 GOPROXY=off GOSUMDB=off GOTOOLCHAIN=local
/ATO/yargs %1 /ATO/options /ATO/yargs %2 /ATO/arguments go run %1 /ATO/code.go %2 < /ATO/input
