#!/bin/sh -e
# Build a package to be used by the setup script when installing.

rm -rf dist
mkdir -p dist/judgment

echo Building frontend... >&2
cd ..
# clean up previous build artefacts; otherwise nothing seems to properly update
rm -rf .next out
pnpm run build
cd judgment

echo Compiling binaries... >&2
cargo build --release
# 使用已经修改过的 yargs.c 编译
gcc -Wall -Werror -static yargs.c -o dist/judgment/yargs

echo Building tarball... >&2
cp target/release/judgment dist/judgment/server
# list images
jq -r '.[].image' <languages.json | sort -u >dist/judgment/images.txt
cp -R ../out dist/judgment/public
cp -R \
	setup/ 
	runners/ 
	dist/judgment/
cd dist
tar -czf judgment.tar.gz judgment